"""
Polymarket API Credential Generator

Reads wallet credentials from 'pre_setup.env', generates API keys,
and writes the complete config to '.env'.

Usage:
  1. Fill in pre_setup.env:
       POLY_PRIVATE_KEY=0x...
       POLY_FUNDER_ADDRESS=0x...

  2. Run:
       python setup.py

  3. Your .env will be created with all credentials ready for the bot.
"""

import os
import sys
from dotenv import dotenv_values, set_key
from py_clob_client.client import ClobClient
from py_clob_client.constants import POLYGON
from py_clob_client.clob_types import BalanceAllowanceParams, AssetType

PRE_SETUP_FILE = "pre_setup.env"
OUTPUT_FILE = ".env"


def run_setup():
    # ── Read from pre_setup.env ───────────────────────────────────
    if not os.path.exists(PRE_SETUP_FILE):
        print(f"❌ '{PRE_SETUP_FILE}' not found.")
        print(f"   Create it with:")
        print(f"     POLY_PRIVATE_KEY=0x...")
        print(f"     POLY_FUNDER_ADDRESS=0x...")
        sys.exit(1)

    pre = dotenv_values(PRE_SETUP_FILE)
    pk = pre.get("POLY_PRIVATE_KEY", "").strip()
    funder = pre.get("POLY_FUNDER_ADDRESS", "").strip()

    if not pk:
        print("❌ POLY_PRIVATE_KEY is missing in pre_setup.env")
        sys.exit(1)

    print("--- 🔑 Generating API Credentials ---")
    print(f"  Private key: {pk[:6]}...{pk[-4:]}")
    print(f"  Funder: {funder or '(not set)'}")

    # ── Initialize CLOB client ────────────────────────────────────
    client = ClobClient(
        host="https://clob.polymarket.com",
        key=pk,
        chain_id=POLYGON,
        funder=funder or None,
    )

    # ── Derive API credentials ────────────────────────────────────
    creds = client.create_or_derive_api_creds()
    print(f"  API Key:        {creds.api_key}")
    print(f"  API Secret:     {creds.api_secret[:8]}...")
    print(f"  API Passphrase: {creds.api_passphrase[:8]}...")

    # ── Write .env ────────────────────────────────────────────────
    # Create .env if it doesn't exist
    if not os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "w") as f:
            f.write("# Generated by setup.py\n")

    set_key(OUTPUT_FILE, "POLY_PRIVATE_KEY", pk)
    set_key(OUTPUT_FILE, "POLY_FUNDER_ADDRESS", funder)
    set_key(OUTPUT_FILE, "POLY_API_KEY", creds.api_key)
    set_key(OUTPUT_FILE, "POLY_API_SECRET", creds.api_secret)
    set_key(OUTPUT_FILE, "POLY_API_PASSPHRASE", creds.api_passphrase)
    set_key(OUTPUT_FILE, "POLY_SIG_TYPE", "0")

    # ── Re-initialize client with full Level 2 credentials ───────
    from py_clob_client.clob_types import ApiCreds
    client = ClobClient(
        host="https://clob.polymarket.com",
        key=pk,
        chain_id=POLYGON,
        funder=funder or None,
        creds=ApiCreds(
            api_key=creds.api_key,
            api_secret=creds.api_secret,
            api_passphrase=creds.api_passphrase,
        ),
    )

    # ── Set allowance ─────────────────────────────────────────────
    print("\n--- 🛡️ Setting USDC.e Allowance ---")
    try:
        client.update_balance_allowance(
            params=BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        )
        print("  ✅ Allowance set.")
    except Exception as e:
        print(f"  ⚠️  Allowance failed: {e}")

    # ── Verify allowance was actually registered ──────────────────
    print("\n--- 🔍 Verifying Balance & Allowance ---")
    try:
        resp = client.get_balance_allowance(
            params=BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        )
        raw_balance = resp.get("balance", 0) if isinstance(resp, dict) else getattr(resp, "balance", 0)
        raw_allowance = resp.get("allowance", 0) if isinstance(resp, dict) else getattr(resp, "allowance", 0)
        balance = float(raw_balance or 0)
        allowance = float(raw_allowance or 0)
        if balance > 1_000_000:
            balance /= 1e6
        if allowance > 1_000_000:
            allowance /= 1e6
        print(f"  Balance:   ${balance:.2f} USDC")
        print(f"  Allowance: ${allowance:.2f} USDC")
        if allowance == 0:
            print("  ❌ Allowance is still 0 — the bot will not be able to trade!")
            print("     Try running setup.py again, or approve manually on app.polymarket.com")
        else:
            print("  ✅ Allowance confirmed. Bot is ready to trade.")
    except Exception as e:
        print(f"  ⚠️  Could not verify: {e}")

    print(f"\n✅ Done! Credentials written to '{OUTPUT_FILE}'")
    print(f"   You can now run: python bot.py")


if __name__ == "__main__":
    run_setup()
